version: "3"


tasks:
  init:
    cmds:
      - aqua install --only-link
  build:
    cmds:
      - go build
  run:
    deps:
      - build
    cmds:
      - ./toy-omochice-releaser
  fmt:
    shopt:
      - globstar
    cmds:
      - goimports -w ./**/*.go
